stages:
  - build
  - test

build:
  image: django
  stage: build
  script:
    - pip install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate

test:
  image: django
  stage: test
  script:
    - pip install -r requirements.txt
    - python3 manage.py test