stages:
- build
- test
- deploy
before_script:
- npm install -g create-react-app
build-frontend:
  stage: build
  image: node
  script:
  - npm install
  - npm run build
  only:
  - master
test-frontend:
  stage: test
  image: node
  script:
  - npm install
  - CI=true npm test
  only:
  - master
deploy-frontend:
  stage: deploy
  image: node
  script:
  - npm run build
  - cp .env.production build/.env
  - rsync -avz --delete-after --quiet $CI_PROJECT_DIR/build/ user@yourserver:/var/www/your-react-app/
  environtment:
    name: production
  only:
  - master
