cache:
  paths:
  - .cahce/pip
  - node_modules/
stages:
- build
- test
- deploy
before_script:
- python -m pip install --upgrade pip
- pip install poetry
- poetry install --no-dev
build-backend:
  stage: build
  image: python
  script:
  - pip install -r requirements.txt
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  artifacts:
    paths:
    - build/
  only:
  - master
test-backend:
  stage: test
  image: python
  script:
  - pip install -r requirements.txt
  - python3 manage.py test
  only:
  - master
deploy-backend:
  stage: deploy
  image: python
  script:
  - pip install -r requirements.txt
  - bash ./deploy.sh
  only:
  - master
