# Generated by Django 4.1.3 on 2022-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.CharField(default='000000', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='stages',
            field=models.CharField(default='000000', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='000000', max_length=30),
        ),
    ]
