# Generated by Django 4.1.3 on 2022-12-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_project_repo_project_stages_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='projectDescription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='projectName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='repo',
            new_name='projectType',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='repoType',
        ),
    ]
